openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /api/series:
    get:
      summary: Get paginated list of series with related genres, studios, and themes
      responses:
        '200':
          description: A paginated list of series
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: "Example Series Title"
                        genres:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: 10
                              name:
                                type: string
                                example: "Action"
                        studios:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: 5
                              name:
                                type: string
                                example: "Studio Ghibli"
                        themes:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: 3
                              name:
                                type: string
                                example: "Adventure"
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: "/api/series?page=1"
                      last:
                        type: string
                        example: "/api/series?page=10"
                      prev:
                        type: string
                        nullable: true
                        example: null
                      next:
                        type: string
                        nullable: true
                        example: "/api/series?page=2"
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 10
                      path:
                        type: string
                        example: "/api/series"
                      per_page:
                        type: integer
                        example: 15
                      to:
                        type: integer
                        example: 15
                      total:
                        type: integer
                        example: 150
